name: Format
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: --format github
      - uses: psf/black@stable
        with:
          options: "--check"
      - name: Format SQL
        run: |
          pip install sqlfluff
          sqlfluff fix metrics --dialect postgres --force
