name: Format
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./scripts"
      - uses: psf/black@stable
        with:
          options: "--check"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install packages
        run: uv sync
      - name: Type check
        run: uvx ty check .
      - name: Check SQL
        run: uvx sqlfluff lint metrics --dialect postgres
      - name: Format SQL
        run: uvx sqlfluff fix metrics --dialect postgres
