name: Format
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: --format github
      - uses: psf/black@stable
        with:
          options: "--check"
      - uses: jitsucom/sqlfluff-action@v1
        with:
          dialect: postgres
          paths: "metrics/**/*.sql"
